package sapcontrol;

/**
 * Service implementation of {SAPControl} (generated by SAP WSDL to Java generator).
 */
@javax.xml.ws.WebServiceClient(name = "SAPControl", targetNamespace = "urn:SAPControl", wsdlLocation = "WEB-INF/wsdl/sapcontrol/SAPControl/SAPControl.wsdl")
public class SAPControl extends javax.xml.ws.Service {

  private final static java.net.URL SAPCONTROL_WSDL_LOCATION = null;
  /**
   * Default service constructor.
   */
  public SAPControl() throws java.net.MalformedURLException {
//    super(SAPCONTROL_WSDL_LOCATION, new javax.xml.namespace.QName("urn:SAPControl", "SAPControl"));
	  super(new java.net.URL("http://localhost:50313/?wsdl"), new javax.xml.namespace.QName("urn:SAPControl", "SAPControl"));
  }
  public SAPControl(java.net.URL wsdlLocation, javax.xml.namespace.QName serviceName) {
    super(wsdlLocation, serviceName);
  }
  /**
   * Get method for webservice port [SAPControl].
   */
  @javax.xml.ws.WebEndpoint(name = "SAPControl")
  public sapcontrol.SAPControlPortType getSAPControl() {
    javax.xml.namespace.QName portName = new javax.xml.namespace.QName("urn:SAPControl","SAPControl");
    return (sapcontrol.SAPControlPortType) super.getPort(portName,sapcontrol.SAPControlPortType.class);
  }
}
